site_name: MkDocs Nav Manager
nav:
  - Section 1:
    - section1/index.md
    - Page 2: section1/page2.md
    - subsection:
      - section1/subsection/page3.md
      - 33r:
        - section1/subsection/33r/README.md
        - '33': section1/subsection/33r/33.md
      - '2332':
        - section1/subsection/2332/README.md
        - '11': section1/subsection/2332/11.md
        - '22':
          - section1/subsection/2332/22/README.md
          - ss:
            - section1/subsection/2332/22/ss/README.md
            - '444':
              - section1/subsection/2332/22/ss/444/README.md
              - '99': section1/subsection/2332/22/ss/444/99.md
              - '77':
                - section1/subsection/2332/22/ss/444/77/README.md
                - '99': section1/subsection/2332/22/ss/444/77/99.md
            - '22': section1/subsection/2332/22/ss/22.md
            - ww:
              - section1/subsection/2332/22/ss/ww/README.md
