site_name: Mock test
nav:
- Guide:
  - æ˜¯ds:
    - sda: s da/ds/sda.md
  - love123:
    - heihie: s da/123/heihie.md
    - jdskds: s da/123/jdskds.md
    - lo: s da/123/lo.md
  - setup.md: s da/setup.md
  - kjlk:
    - uiiu: s da/dsds/uiiu.md
