site_name: MkDocs Nav Manager
nav:
  - Home:
    - home/index.md
    - ss: home/ss.md
  - Section 1:
    - section1/index.md
    - Page 2: section1/page2.md
    - subsection:
      - section1/subsection/page3.md
    - Page 1: section1/page1.md
  - Section 2:
    - section2/README.md
    - Section 3: section2/index2.md
    - Page A: section2/page.md
    - aa: section2/aa.md
